name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check lint
      run: |
        pre-commit run --all-files

    - name: Build docker image
      run: |
        docker build -t pangtok:latest .

    - name: Run tests in docker container
      run: |
        docker run --rm pangtok:latest python -m pytest
